modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/NucleoidMC/DisguiseLib/issues"
license = "MIT"

[[mods]]
modId = "disguiselib"
version = "${version}"
displayName = "DisguiseLib"
displayURL="https://github.com/NucleoidMC/DisguiseLib"
authors = "samo_lego"
description = '''
A (server-side) library for disguising entities in Minecraft.
'''
logoFile = "icon.png"

[[dependencies.disguiselib]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.disguiselib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "SERVER"